version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/spring-petclinic-2.4.0.BUILD-SNAPSHOT.jar
