version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/spring-petclinic-2.4.0.BUILD-SNAPSHOT.jar spring-petclinic.jar
artifacts:
  files:
    - spring-petclinic.jar
